on: ["push", "pull_request"]
name: "Continuous Integration"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.15.4
      - run: npm install
      - run: npm run build
      - run: npm test
